export default {
  MISSING_MESSAGE_TEXT_PROP: 'MISSING_MESSAGE_TEXT_PROP',
  MISSING_CONTEXT_PROP: 'MISSING_CONTEXT_PROP',
  MISSING_TASK_STATUS_SCENE_PROP: 'MISSING_TASK_STATUS_SCENE_PROP',
  TASK_DOESNT_EXIST: 'TASK_DOESNT_EXIST',
  ALIAS_DOESNT_EXIST: 'ALIAS_DOESNT_EXIST',
  UNRECOGNIZED_TELEGRAF_SCENE: 'UNRECOGNIZED_TELEGRAF_SCENE'
};
